import type { Metadata, Viewport } from 'next'
import { IBM_Plex_Mono, Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import { Pwa } from '@/components/pwa'
import { SITE } from '@/lib/site'
import './globals.css'

/**
 * SF Pro and SF Mono are not webfont-licensable, and they are what the design
 * is drawn in. The token stack puts the system SF families first, so on Apple
 * hardware these two are never fetched at all; elsewhere they carry the same
 * prose/metadata split. Self-hosted by next/font, so metadata never reflows.
 */
const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' })
const plexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-plex-mono',
  display: 'swap',
})

/**
 * Generated by scripts/splash.mjs. Without these Safari flashes white on every
 * launch of the installed app, which is the single loudest tell that a PWA is
 * a web page wearing an icon.
 */
const SPLASH = [
  [1320, 2868, 3, 'iphone-16-pro-max'],
  [1206, 2622, 3, 'iphone-16-pro'],
  [1290, 2796, 3, 'iphone-15-pro-max'],
  // also the 15 Pro and 15 — same logical size
  [1179, 2556, 3, 'iphone-16'],
  [1170, 2532, 3, 'iphone-13'],
  [1284, 2778, 3, 'iphone-12-pro-max'],
  [1125, 2436, 3, 'iphone-x'],
  [828, 1792, 2, 'iphone-xr'],
  [750, 1334, 2, 'iphone-8'],
  [1640, 2360, 2, 'ipad-air'],
  [2048, 2732, 2, 'ipad-pro-12'],
] as const

export const metadata: Metadata = {
  title: SITE.name,
  description: SITE.description,
  appleWebApp: {
    capable: true,
    title: SITE.name,
    statusBarStyle: 'black-translucent',
    startupImage: SPLASH.map(([w, h, ratio, name]) => ({
      url: `/splash/${name}.png`,
      media: `(device-width: ${w / ratio}px) and (device-height: ${h / ratio}px) and (-webkit-device-pixel-ratio: ${ratio})`,
    })),
  },
  icons: { apple: '/icons/apple-touch-icon.png' },
  other: {
    // Next 16 emits `mobile-web-app-capable` but not the Apple-prefixed tag —
    // and iOS only shows the startupImage splash set when the Apple one is
    // present. Without this line all nine generated splash PNGs are dead.
    'apple-mobile-web-app-capable': 'yes',
  },
}

export const viewport: Viewport = {
  viewportFit: 'cover',
  interactiveWidget: 'resizes-content',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#fbf9f5' },
    { media: '(prefers-color-scheme: dark)', color: '#151418' },
  ],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${plexMono.variable}`} data-surface="ledger">
      <body>
        {/* Ledger paper palette. Element-level overrides (hairlines instead of
            Clerk's default card borders) land with the design system in phase 3. */}
        <ClerkProvider
          appearance={{
            variables: {
              colorPrimary: '#2a251d',
              colorPrimaryForeground: '#fbf9f5',
              colorBackground: '#fbf9f5',
              colorForeground: '#2a251d',
              colorMutedForeground: 'rgba(42,37,29,0.55)',
              colorInput: '#ffffff',
              colorInputForeground: '#2a251d',
              colorBorder: 'rgba(42,37,29,0.14)',
              colorDanger: '#a8552b',
              colorSuccess: '#5b8c5a',
              fontFamily: 'var(--font-sans)',
              fontFamilyMono: 'var(--font-mono)',
              borderRadius: '7px',
            },
          }}
        >
          {children}
          <Pwa />
        </ClerkProvider>
      </body>
    </html>
  )
}
